name: Daily XGBoost Retraining

on:
  schedule:
    # "15 0 * * *" means 00:15 UTC (which is exactly 5:15 AM PKT)
    - cron: '15 0 * * *'
  workflow_dispatch:

jobs:
  train-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        working-directory: ./backend
        run: pip install -r requirements.txt

      - name: Run Training Script
        working-directory: ./backend
        env:
          # Passing all the secrets from GitHub to the Python script
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          R2_BUCKET_NAME: ${{ secrets.R2_BUCKET_NAME }}
          R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
          R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
          R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
          VITE_API_URL: ${{ secrets.PROD_API_URL }}
          WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
        run: python train_model.py